// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Tool is the golang structure of table tool for DAO operations like Where/Data.
type Tool struct {
	g.Meta     `orm:"table:tool, do:true"`
	Id         interface{} // pk
	Tid        interface{} // Tool ID
	Name       interface{} // Tool Name
	Desc       interface{} // Description
	Price      interface{} // Tool Price
	Url        interface{} // Tool url
	Type       interface{} // Tool Type
	Author     interface{} // Tool Author
	Avatar     interface{} // Tool 图片
	CreateTime *gtime.Time // Created Time
	UpdateTime *gtime.Time // Updated Time
}
